name = "BabelNAR_Implements"
uuid = "28c5d3c6-c8be-47e2-a215-fc9784cf8bbd"
authors = ["ARCJ137442 <61109168+ARCJ137442@users.noreply.github.com>"]
version = "0.4.0"

[deps]
BabelNAR = "b7421120-50f0-43fc-8b2b-7721c3d5cbfc"
NAVM = "2245f648-40fa-438d-8bb4-5b93bf8a933b"
NAVM_Implements = "60a2844f-9e68-4e7b-855c-e56e218f0267"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
